name: Catalog Service

on:
  push:
    paths:
      - catalog-Service/**
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working_directory: ./catalog-Service
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: chmod +x -ntp verify
